[project]
name = "llm-dag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=3.4.3",
    "matplotlib>=3.10.1",
    "networkx>=3.4.2",
    "scipy>=1.15.2",
]
